{
	"records": [{
		"Title": "Project1",
		"StartDate": "01/02/2017",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "300000",
		"ApprovedExtraCost": "10000",
		"WorkingWeek": "Mon-Sun",
		"SchedulingMode": "Manual",
		"Progress": "90%",
		"State": "Problem"
	}, {
		"Title": "Project2",
		"StartDate": "01/01/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "100%",
		"State": "Verified"
	}, {
		"Title": "Project3",
		"StartDate": "11/02/2016",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "100%",
		"State": "Awaiting sign-off"
	}, {
		"Title": "Project4",
		"StartDate": "12/08/2016",
		"EndDate": "03/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "38%",
		"State": "In progress"
	}, {
		"Title": "Project5",
		"StartDate": "01/02/2016",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Not started"
	}, {
		"Title": "Project6",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project7",
		"StartDate": "01/09/2017",
		"EndDate": "01/09/2017",
		"Milestone": 1,
		"Tag": "Tag1",
		"Assignee": "Zawisza Czarny",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project8",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project9",
		"StartDate": "01/02/2017",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project10",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Tag": "Tag2",
		"Milestone": 0,
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project11",
		"StartDate": "01/02/2017",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project12",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project13",
		"StartDate": "01/02/2017",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Król Karol",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project14",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project15",
		"StartDate": "01/02/2017",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project16",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project17",
		"StartDate": "01/02/2017",
		"EndDate": "01/09/2017",
		"Milestone": 0,
		"Tag": "Tag1",
		"Assignee": "Zyndram z Maszkowic",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}, {
		"Title": "Project18",
		"StartDate": "01/08/2017",
		"EndDate": "01/11/2017",
		"Milestone": 0,
		"Tag": "Tag2",
		"Assignee": "Anatol Kowalski",
		"Budget": "200000",
		"ApprovedExtraCost": "0",
		"WorkingWeek": "Mon-Fri",
		"SchedulingMode": "Automatic",
		"Progress": "0%",
		"State": "Problem"
	}]
}